# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5cdb9b90caba47a99e29a2c0a2be57cd4991bafc2ebecceb7bc5443ee764559460e072e4caa49b9c4ca2f470c322d0647a658eb39bf946359408cda773b78ec

test:
  secret_key_base: e1dc4e9dda5bff66f6678022fb856c0d6937af7c8fb91c15d8c3f88d0b87cf0af37ba4530b25920d2c0cd4a6ded5356870a5f29887a365592f897b61e4ad4ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
